# Generated by Django 2.2.24 on 2021-06-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transactions',
        ),
    ]
